// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VShifting_reg_test.cpp"
#include "VShifting_reg_test___024root.cpp"
#include "VShifting_reg_test__Trace.cpp"
#include "VShifting_reg_test___024root__Slow.cpp"
#include "VShifting_reg_test__Syms.cpp"
#include "VShifting_reg_test__Trace__Slow.cpp"
